version: '3.7'
services:
  api:
    container_name: hhplus-app
    image: hhplus-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    volumes:
        - .:/src
    networks:
      - hhplus-network
networks:
  hhplus-network:
    driver: bridge
