version: '3.7'
services:
  redis:
    container_name: hhplus-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hhplus-network
    restart: always
  api:
    container_name: hhplus-app
    image: hhplus-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    depends_on:
      - redis
    networks:
      - hhplus-network
networks:
  hhplus-network:
    driver: bridge
